### ISSUE TITLE
Provide python stack trace on Python Error

### ISSUE THREAD

**Issue by bartdag** [bartdag/py4j#137]
As reported by a user of Py4J, exceptions thrown by Python (e.g., in a Python callback) are swallowed by a Py4JException: they are correctly reported, but the trace is lost.

One solution would be to use the same protocol that we have on the Python Side: if Java throws an error, it can include the stack trace after the "x" (protocol token indicating that an exception occurred).

**Comment by sangeeta28** [comment]
Hi, I have a very basic pyspark code running on an EMR cluster. I am using log4j for logging. I got my logger from the sparkcontext using logger = sc._jvm.org.apache.log4j.Logger.getLogger(__name__)
But, I am not unable to log an exception stacktrace to this logfile. Is there a way to log everything to a log file?

**Comment by torokati44** [comment]
I'd like to just quietly signal my interest in seeing this issue resolved. It would make Py4J so much more useful!

**Comment by scottslewis** [comment]
>I'd like to just quietly signal my interest in seeing this issue resolved. It would make Py4J so much more >useful!

+1.   FWIW Barthelemy, now the osgiservicebridge makes it relatively easy to expose multiple python objects as osgi service instances this error display is more obviously a problem...since the python impl of any of the instances can throw...and just gets back to java as a generic protocol error...i.e. nothing to tell what went wrong.
