### ISSUE TITLE
Use random port for Python callback server

### ISSUE THREAD

**Issue by davies** [bartdag/py4j#147]
We could use `0` as random port in Python Gateway, but can not get the real port which callback server was binded, and update the Java callback client.

**Comment by 243826** [comment]
I feel that this is similar to what I have been exploring. Let me explain my use  case:

1. Java Process Starts.
2. Java GatewayServer starts listening on port 0.
3. Communicates the actual port on which it's listening to Python Process which connects to this port and additionally starts a callbackserver on port 0.
4. Communicates the actual callbackserver port using entry point to JVM
5. JVM registers that as a port for CallbackClient

I think I am able to do 1-4. 5th although trivial to implement - I was wondering if there is a better workflow than what I am thinking to make both the processes to interoperate.

Please comment. I can work on the PR if you feel I am on the right track.

**Comment by bartdag** [comment]
I guess in py4j.java_gateway.JavaGateway, we could add a method start_dynamic_callback_server(), which would:

1. Start the callback server on port 0
2. Communicate the port to the Java side (with a new command, because the GatewayServer instance is not accessible?)
3. Once receiving the port, the Java side would create a new CallbackClient with the port.

Would that be acceptable @davies ?

@243826 I am not sure how you would accomplish step 3: would the JVM starts the Python process?

**Comment by davies** [comment]
@bartdag lgtm

**Comment by 243826** [comment]
@bartdag  After I was done implementing something on my end - I reread what @davies wanted. Realized that I wanted opposite of what he wanted. The main difference is that in my case JVM tells another agent to launch Python. This way I avoid parent/child relationship between the 2 processes. 

On the python side - I made the following change:
1. Provision to listen on port 0 was always there. I pass the callback server port explicitly as zero in my application. So no change there.
2. I added methods to query back the listening_port just the way Java api provides one.

I have not worked on special command to communicate the port since in my case I know the GatewayServer instance. Should I send in the PR for review?

**Comment by bartdag** [comment]
Yes, I would like to see this. Methods that allow better introspection are definitively welcome.

Instead of a new command, I might just add a way to target the GatewayServer (e.g., gateway.java_server) which would allow greater customization.

Thanks!

**Comment by bartdag** [comment]
@davies this is the solution @243826 contributed (I merely merged it and I added a java_gateway_server field to JavaGateway). Let me know if it works for you.

**Comment by davies** [comment]
@bartdag @243826 That works for me, thanks! Will upgrade to 0.9.1 once it's released.
