### ISSUE TITLE
auto_convert does not work with bytearray

### ISSUE THREAD

**Issue by davies** [bartdag/py4j#160]
bytearray is iterable, ListConverter will convert it into ArrayList, It should only convert list.

**Comment by bartdag** [comment]
The latest commit should fix the issue. I also added an optional parameter to register_input_converter to allow client code to insert a converter to bypass default converters. Note that I no longer check by default if an object is a string before trying to convert it (this is the responsibility of the converter).

There was a small catch: to support ducktyping, autoconvert will try to convert any sequence-like objects in Python, not just List instance. But because bytearray is a type already handled by the protocol, it does not make sense to convert it to a list so I excluded bytearrays as requested by your bug report.

**Comment by davies** [comment]
Thanks!
