### ISSUE TITLE
Add listener for connection events on Python side

### ISSUE THREAD

**Issue by scottslewis** [bartdag/py4j#240]
On the java side it's possible to define/add a listener for connection events via:

GatewayServer.addListener(serverListenerImpl)

Having this listener on the GatewayServer is very helpful for supporting  the dynamics of the OSGi service registry, as connection can be forcibly closed by breaking the socket or the Python process can crash.  See the work I've been doing on supporting the dynamics of the OSGi service registry across Python <-> Java here:  https://github.com/ECF/Py4j-RemoteServicesProvider

On the Python side it would be useful to have a similar listener...perhaps on CallbackServer.addListener, or via CallbackServerParameters or both?

I'm of the opinion that it should 'look' as much like the GatewayEventListener as possible...for convenience.   See some discussion on this issue here:

https://groups.google.com/a/py4j.org/forum/?utm_medium=email&utm_source=footer#!topic/py4j/sBcEfxSrYwk

I would be willing to work/contribute to implementing this if desired.   I need some personal resources to do so in a timely manner, however.

**Comment by bartdag** [comment]
Thanks Scott for reporting this issue and providing a use case. The RemoteServicesProvider look very interesting!

What I meant about the signal pattern is that the observer pattern is usually implemented in Python with signals: instead of registering one class that has one method per event type, you register one function (receiver) per event (signal). You can still implement your observer as a class with many methods.

There are other options usually associated with signals (e.g., possibility to treat receivers as weak references), but I don't think it's needed here. I do not intend to re-implement the whole Django signals module in Py4J, just a generic way to declare and register signals. 

I should be able to implement this soonish because it's a very small addition and I was looking for a feature I could add to 0.10.3 considering that all the other large features were moved to 0.11

**Comment by bartdag** [comment]
@scottslewis This took a lot longer than expected because I ended up working on a potential memory leak problem. Before adding a necessary back reference in one of the Python class, I created a more advanced memory leak unit test that uncovered a few issues (wrong sequence of socket operation that is a potential problem in Python 3 only and a potential memory leak in the clientserver Java code).

You can see a full usage example in the documentation here: https://github.com/bartdag/py4j/blob/master/py4j-web/advanced_topics.rst#listening-to-server-events

The events are the same as the ones declared in GatewayServerListener. I used the signal pattern because it is a lot more common in the Python world than the Observer/Listener pattern (this usually looks strange when you come from the Java world).

**Comment by scottslewis** [comment]
@bartdag it all sounds good.    I'm fine with the signal approach...allows me to get more familiar with Pythonics :)  I'll take a look at the code and give it a try with my OSGi bridge...to detect hard disconnects and allow cleanup on Python side.

Just FYI...you might be interested in the OSGi services notion of listeners (whiteboard pattern):   

https://www.osgi.org/wp-content/uploads/whiteboard1.pdf

avoids the problems of registration/unregistration associated with listeners.

**Comment by bartdag** [comment]
Didn't know about the whiteboard pattern/ServiceTracker. Thanks!

**Comment by scottslewis** [comment]
I've tried things out and the signals appear to work ok.   Thanks very much for the work.   One question:  I received the connection_stopped signal after forcibly closing the GatewayServer (killing process), but I noticed that in the kwargs there was no exception info.  The exception info is printed out...e.g.:

INFO:py4j.java_gateway:Error while callback connection was waiting fora message
Traceback (most recent call last):
  File "C:\Users\slewis\git\py4j\py4j-python\src\py4j\java_gateway.py", line 2088, in run
    command = smart_decode(self.input.readline())[:-1]
  File "C:\Users\slewis\Anaconda3\lib\socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
INFO:py4j.java_gateway:Closing down callback connection
Py4j gateway connection stopped=<CallbackConnection(Thread-8, started 7892)>

but the exception (in this case ConnectionResetError is not provided to the connectionStopped.  Would it make sense to do so?   Again many thanks....This will be most useful.

**Comment by bartdag** [comment]
Hi Scott, it makes sense to include the exception info from a user perspective, but the change requires pushing down exception information and there isn't always an exception to provide. I guess that providing the exception in GatewayServerListener.connectionStopped would also make sense. Could you open a new issue for that? Thanks!

**Comment by scottslewis** [comment]
Hi Barthelemy,

In using this I'm noticing something I don't understand.   First, I'm dealing with the Python side.

Here's the code for CallbackConnection.run()

    def run(self):
        logger.info("Callback Connection ready to receive messages")
        reset = False
        try:
            while True:
                command = smart_decode(self.input.readline())[:-1]
                obj_id = smart_decode(self.input.readline())[:-1]
                logger.info(
                    "Received command {0} on object id {1}".
                    format(command, obj_id))
                if obj_id is None or len(obj_id.strip()) == 0:
                    break
                if command == proto.CALL_PROXY_COMMAND_NAME:
                    return_message = self._call_proxy(obj_id, self.input)
                    self.socket.sendall(return_message.encode("utf-8"))
                elif command == proto.GARBAGE_COLLECT_PROXY_COMMAND_NAME:
                    self.input.readline()
                    del(self.pool[obj_id])
                    self.socket.sendall(
                        proto.SUCCESS_RETURN_MESSAGE.encode("utf-8"))
                else:
                    logger.error("Unknown command {0}".format(command))
                    # We're sending something to prevent blokincg, but at this
                    # point, the protocol is broken.
                    self.socket.sendall(
                        proto.ERROR_RETURN_MESSAGE.encode("utf-8"))
        except socket.timeout:
            reset = True
            logger.info(
                "Timeout while callback connection was waiting for"
                "a message", exc_info=True)
        except Exception:
            # This is a normal exception...
            logger.info(
                "Error while callback connection was waiting for"
                "a message", exc_info=True)
        self.close(reset)

What I'm seeing is that after *about thirty seconds of no traffic* the blocking read call...i.e.:

                command = smart_decode(self.input.readline())[:-1]

returns with a command of "", I see this in the logger:

$ INFO:py4j.java_gateway:Received command  on object id 

and the 'break' is executed, which means that the while True loop is exited, the close(reset=False) method is called, and the connection_stopped signal is sent to my listener.

But then if I subsequently kill the java process (again via the debugger), no signal is sent to my listener.   This is a problem, as I would like to be able to detect the crash of the java process and remove and Java object proxies only when the connection is broken...but not when it 'dies naturally' via the Received command "" on object id "", break, and close(False).

Is this the expected behavior?  Is there any way to get a signal about the disconnect?

**Comment by bartdag** [comment]
Hi Scott,

I believe what you are describing is expected as everything is created on demand and there is no heartbeat currently implemented.

> What I'm seeing is that after about thirty seconds of no traffic the blocking read call...i.e.:

So this is a bit strange. This means that the Java side sent something incomplete. Is it part of your test? Depending how the Java side is implemented you may be seeing the effect of the periodic cleanup (you asked before if it was possible to disable this. it should be, but the appropriate flags do not exist yet), but the periodic cleanup should not do anything to a connection that is being used, so I'm confused how this can happen.

> But then if I subsequently kill the java process (again via the debugger), no signal is sent to my listener. 

Right and it should be the same on the reverse side: if you close the connections (JavaGateway.close()) and then kill the Python process, the GatewayServerListener will not send anything unless you detect the end of the process and shutdown the GatewayServer.

The thing is that once the connections are closed on the server side (GatewayServer or CallbackServer), it's not possible to know if the client is still alive. I believe you would need to implement a heartbeat or to prevent both sides from closing connections until one side shuts down. The heartbeat is probably more reliable because non-localhost connections may close.

**Comment by scottslewis** [comment]
Hi Barthelemy,

>Hi Scott,
>
>I believe what you are describing is expected as everything is created on demand and there is no >heartbeat currently implemented.
>
>What I'm seeing is that after about thirty seconds of no traffic the blocking read call...i.e.:
>So this is a bit strange. This means that the Java side sent something incomplete. Is it part of your test? 

There is nothing being explicitly sent from the Java side.   I thought at first that there was something sending commands automatically from Java side, but I put a breakpoint (on Java side), in py4j.CallbackConnection.sendCommand(String, boolean)

and it was never hit.   Maybe this isn't the right spot in java code to detect it, however.

But on the Python side, the connection was closed automatically after ~30 seconds of inactivity as I described.   I think you should be able to reproduce simply by waiting with no app-level traffic.

>Depending how the Java side is implemented you may be seeing the effect of the periodic cleanup 
>(you asked before if it was possible to disable this. it should be, but the appropriate flags do not exist
>yet), 

I suspect that this is the case (periodic cleanup)...as it does seem to be on regular time schedule.  I think it would be valuable to be able to disable this automatic cleanup, as it may be more important for some use cases to be able to detect disconnection robustly rather than cleanup network resources.

Thanks.  Scott

**Comment by bartdag** [comment]
Hi Scott, not sure why I misread your comment earlier, but this is definitively the periodic cleanup at work there (not sure why I thought the code was blocking at object_id). Adding an option to disable periodic cleanup (and adding periodic cleanup to the python side for good measure) is a good idea, but remember that users can still call .close(), which will have the same effect: you won't be able to tell whether the other side has disconnected because you are back to the initial state where there are no connection.

**Comment by scottslewis** [comment]
Hi Barthelemy,

I'm not sure whether this is clear, so I I want to let you know why this is important for this OSGi service bridge stuff.   If you already know all this, please ignore.

OSGi services are very dynamic...coming and going at runtime.   One of the things about Remote Services that can be quite difficult is detecting communication failure and mapping this failure to the 'departure' of a remote service (i.e. the proxy).   

So what I'm trying to do is...on the Python side...map the failure of the comm and/or the Java side to the departure of the remote service (and subsequent notification and cleanup that can be done).   I happen to be using pelix and ipopo for an 'osgi-like' python environment:  http://ipopo.coderxpress.net/wiki/doku.php but this doesn't require any of that as even just the servicebridge (without pelix/ipopo) could benefit from such a notification for some use cases.

Anyway, that's a short explanation.   I think what would be best would be if 

a) it was possible to disable the automatic/periodic cleanup of connections...or perhaps more generally just have a parameter that determines how frequently it's done (with 'never' being possible).   

b) If the connection_stopped signal has an optional kwargs entry that was the exception responsible for the connection being gone (it could, of course, not be any exception at all...therefore optional).

These two things are sort of bound up together and so please let me know what/how worded you would like the issues/feature requests to be and I'll open them.   Also, I'm willing to help with the technical work (pull requests) if you like as I'm getting more familiar with your code, but don't want to complicate things.  Thanks.

**Comment by bartdag** [comment]
Hi Scott, please open two tickets, they are sufficiently clear. Implementing them shouldn't be too difficult.  It would be great if you can contribute to one or both of these issues. 

To add to what we discussed before, don't forget that there may be multiple concurrent connections so one stopped connection, even with an exception, does not mean that the other side died.
