### ISSUE TITLE
JavaGateway.launch_gateway should respect $JAVA_HOME

### ISSUE THREAD

**Issue by michaelaberman** [bartdag/py4j#245]
On a system with multiple JREs, it would be nice to be able to explicitly choose which one is used when launching py4j's JavaGateway. Right now it appears py4j always uses the bare command `java`, which will resolve to whatever happens to be first on the path. A typical way to control this in other applications is by setting the JAVA_HOME environment variable. If present, it would be nice for JavaGateway to prefer `$JAVA_HOME/bin/java` to straight `java`.

**Comment by bartdag** [comment]
Hi,

Do you mean "Java" in the launch gateway function or are you referring to something else?

**Comment by michaelaberman** [comment]
Updated the title, thanks. Yes, I'm talking about this bit of code in launch_gateway:

```
    command = ["java", "-classpath", classpath] + javaopts + \
              ["py4j.GatewayServer"]
   
    # ... snip...

    proc = Popen(command, stdout=PIPE, stdin=PIPE, stderr=stderr,
                 close_fds=True)
```

**Comment by bartdag** [comment]
OK. I can add an option, java_path. If none, py4j  will check whether Java home is in the environment variable and use it if available. Otherwise it will fall back to java. 

The default in 0.10.3 will be "java", but I'll set it to None in 0.11 (due in maybe two months) because I can afford to make backward incompatible change. 

Would that work with you?

**Comment by michaelaberman** [comment]
That sounds great, thank you.
