### ISSUE TITLE
Cannot set float value in Java array

### ISSUE THREAD

**Issue by ericleib** [bartdag/py4j#255]
I encounter this problem because I need to call a Java method which takes a array of floats as input:
```
void method(float[] input){
   ...
}
```
I can create and fill an array of double:
```
double_class = gateway.jvm.double
double_array = gateway.new_array(double_class, 10)
for i in range(10):
     double_array[i] = 0.0
```
But the same fails with floats:
```
float_class = gateway.jvm.float
float_array = gateway.new_array(float_class, 10)
for i in range(10):
      float_array[i] = 0.0
```

> Py4JError: An error occurred while calling None.None. Trace:
> java.lang.IllegalArgumentException: argument type mismatch
> 	at java.lang.reflect.Array.set(Native Method)

**Comment by bartdag** [comment]
Thanks for the report. The problem is that Py4J does not attempt to perform type conversion/guessing in the case of an array (compared to when you call a method). You would probably have the same problem if you declared a char array and tried to set a string of one character.

It's quite a big limitation, maybe I can make a 0.10.4 release before the 0.11 (which is taking longer than expected).

**Comment by bartdag** [comment]
Just added a fix for array set: it now uses the same type conversion found in the call/constructor command.
