### ISSUE TITLE
Py4JNetworkError: An error occurred while trying to connect to the Java server (127.0.0.1:25335)

### ISSUE THREAD

**Issue by poojapurushotham** [bartdag/py4j#262]
@bartdag  :
Env: win7-x64, 
Python Version: Python 2.7.12
Py4jVersion :0.10.3
java version "1.8.0_101" 

Java Code:
LogDebugCmd.java:
```java
public class LogDebugCmd implements Command {
  private Class clazz;
  private String format;
  private Object[] args;

  public LogDebugCmd() {}
  public Command setLog(String format, Object... args) {
    this.format = format;
    this.args = args.clone();
    clazz = getClass();
    return this;
  }

  @Override
  public void execute() {
    VLog.getLog(clazz).debug(format, args);
  }
```

CommandEntryPoint.java
```java
public class CommandEntryPoint {
  private LogDebugCmd logDebugCmd;

  public CommandEntryPoint() {
    logDebugCmd = new LogDebugCmd();

public LogDebugCmd getLogDebugCmd() {
    return logDebugCmd;
  }
public static void main(String args[]) {
    GatewayServer gatewayServer = new GatewayServer(new CommandEntryPoint());
    gatewayServer.start();
    System.out.println("Gateway Server Started");
  }
```

Python code
test.py:
```python
from py4j.java_gateway import JavaGateway, GatewayParameters
gateway = JavaGateway(gateway_parameters=GatewayParameters(port=25335))
logDebugCmd = gateway.entry_point.getLogDebugCmd()
logDebugCmd.setLog("Hi").execute()
```

 I have my JVM running (through IntelliJ) and then when I run the python code, I am getting the following error :
 Traceback (most recent call last):
```
  File "C:/Python27/Lib/site-packages/py4j-0.10.3-py2.7.egg/py4j/sampleTLStest.py", line 3, in <module>
    logDebugCmd = gateway.entry_point.getLogDebugCmd()
  File "C:\Python27\lib\site-packages\py4j-0.10.3-py2.7.egg\py4j\java_gateway.py", line 1131, in __call__
    answer = self.gateway_client.send_command(command)
  File "C:\Python27\lib\site-packages\py4j-0.10.3-py2.7.egg\py4j\java_gateway.py", line 881, in send_command
    connection = self._get_connection()
  File "C:\Python27\lib\site-packages\py4j-0.10.3-py2.7.egg\py4j\java_gateway.py", line 829, in _get_connection
    connection = self._create_connection()
  File "C:\Python27\lib\site-packages\py4j-0.10.3-py2.7.egg\py4j\java_gateway.py", line 835, in _create_connection
    connection.start()
  File "C:\Python27\lib\site-packages\py4j-0.10.3-py2.7.egg\py4j\java_gateway.py", line 970, in start
    raise Py4JNetworkError(msg, e)
Py4JNetworkError: An error occurred while trying to connect to the Java server (127.0.0.1:25335)
```

**Comment by bartdag** [comment]
Hi,

you are trying to connect to port 25335 on the Python side, but the Java side is listening on the default port, 25333. To fix this, either use the default port on both side, or start the GatewayServer on port 25335 using one of the many constructors.

**Comment by bartdag** [comment]
And thanks for the small code example, if all the bug reports were like that, that would make my life a lot easier :-)

**Comment by poojapurushotham** [comment]
Thank you for the quick reply ! Yes, you are right, Java was listening on the default port. Correcting the port on Java side helped resolve the issue. Appreciate your help ! :)

**Comment by poojapurushotham** [comment]
@bartdag : Can you please take a look at this question?http://stackoverflow.com/questions/40412494/passing-varargs-to-java-from-python-using-py4j

Thanks,
Pooja

**Comment by bartdag** [comment]
I responded to the question.

**Comment by Nikhillosalka** [comment]
Hi @bartdag , @poojapurushotham 

Getting below error while running the above example.
Please help.
/usr/bin/python2.7 "/Users/Nikhil/Library/Application Support/IdeaIC2017.1/python-ce/helpers/pycharm/_jb_unittest_runner.py" --path /Users/Nikhil/Projects/scala-maven-example-master/src/main/javaPythonBinding/test.py
Testing started at 2:48 PM ...
Traceback (most recent call last):

  File "/Users/Nikhil/Library/Application Support/IdeaIC2017.1/python-ce/helpers/pycharm/_jb_unittest_runner.py", line 35, in <module>
    main(argv=args, module=None, testRunner=unittestpy.TeamcityTestRunner, buffer=not JB_DISABLE_BUFFERING)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/main.py", line 113, in parseArgs
    self._do_discovery(argv[2:])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/main.py", line 214, in _do_discovery
    self.test = loader.discover(start_dir, pattern, top_level_dir)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 206, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 267, in _find_tests
    raise ImportError(msg % (mod_name, module_dir, expected_dir))
Launching unittests with arguments python -m unittest discover -s /Users/Nikhil/Projects/scala-maven-example-master/src/main/javaPythonBinding -p test.py -t /Users/Nikhil/Projects/scala-maven-example-master/src/main/javaPythonBinding in /Users/Nikhil/Projects/scala-maven-example-master/src/main/javaPythonBinding
ImportError: 'test' module incorrectly imported from '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/test'. Expected '/Users/Nikhil/Projects/scala-maven-example-master/src/main/javaPythonBinding'. Is this module globally installed?

**Comment by MahanteshAngadiGH** [comment]
Hi All,

I am also facing the similar problem as in this thread start.

I am running a series of iPython scripts in a Jupyter Notebook in a Chrome browser on an EMR cluster.
In between it failed with an error of:

ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)
Traceback (most recent call last):
  File "/usr/lib/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
  File "/mnt1/anaconda2/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

From the error, I felt that, the connection to the Java server has been lost.

1. First of all what is the reason for this connection failure?
2. Can I re-establish the connection and continue my iPython scripts execution from the point of failure?

I am very new, the answers with detailed steps would really be appreciated.

Thanks in advance.

Regards,
Monty

**Comment by anuthaharinimn** [comment]
hi , i have an python service and the java , its depends on each other, im getting this error iside the container, how to resolve this issue

**Comment by smomen** [comment]
@anuthaharinimn try increasing your docker memory, it worked for me

**Comment by AyaAlqurashi** [comment]
@MahanteshAngadiGH 
did u find an answer for your question ?!
i'm facing the same problem and till now i couldn't find a solution

**Comment by MahanteshAngadiGH** [comment]
Hi, you need to adjust (increase) the executor memory & memoryOverload

**Comment by raksja** [comment]
Same exact issue is happening to me as well.
Any else have a solution, increasing memory on executor and driver didnt help..

**Comment by smomen** [comment]
@raksja how are you increasing memory on executor and driver? can't do it through spark config, as the jvm is already up and running - have to do it through pyspark submit args.

**Comment by smomen** [comment]
(verify in the Environment tab of the spark UI that you are indeed getting the memory increase you desire)

**Comment by AyaAlqurashi** [comment]
@smomen
Could u plz explain more how we can increase the memory via spark submit
args and how we will verify in the environment to to get the desired
increase in the memory !!

**Comment by smomen** [comment]
@AyaAlqurashi yes, i followed this post and it worked for me https://stackoverflow.com/a/39644647/5770938

**Comment by smomen** [comment]
you can usually access the spark UI at localhost:4040 (when the job is running), where there is information about the spark environment... there may be a better way that i don't know about.

**Comment by MahanteshAngadiGH** [comment]
Hi  smomen,

You can add the following to your configuration in AWS Console while
setting/creating the EMR cluster. There is configuration tab (the very
first)

*1. Java Server Error : This is due to the time out while processing*

*Sample of Error Message*
ERROR:py4j.java_gateway:An error occurred while trying to connect to the
Java server (aaa.bbb.ccc.ddd:nnnnnn)

Required Configuration Change
,{"classification":"hive-site","properties":
    {"hive.spark.client.server.connect.timeout":"360000ms"}
 }


*2. Java Server Error : This is due to the time out while processing*
*Sample of Error Message*
Reason: Container killed by YARN for exceeding memory limits.
5.5 GB of 5.5 GB physical memory used.
Consider boosting spark.yarn.executor.memoryOverhead.

Required Configuration Change
,{"classification":"spark-defaults","properties":

{"spark.executor.memory":"10G","maximizeResourceAllocation":"true","spark.executor.memoryOverhead":"3G","spark.executor.instances":"20"}
}

*Note:* You might require to calculate these configuration parameters.


Regards,
Monty

**Comment by raksja** [comment]
@smomen @MahanteshAngadiGH 
I have increased the memory as you have specified as well. It didnt help.. this the whole stacktrace of what am getting, when i submit a py spark app with yarn cluster mode.

`ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:46305)
Traceback (most recent call last):
  File "/mnt/yarn/.../container_1520453695291_0094_01_000001/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
  File "/usr/lib64/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused`

**Comment by MahanteshAngadiGH** [comment]
Did you try the server connect timeout configuration
,{"classification":"hive-site","properties":
    {"hive.spark.client.server.connect.timeout":"360000ms"}
 }

**Comment by raksja** [comment]
This looks like a hive config, but am getting this issue when i do spark submit with Python file. Am I missing anything?

**Comment by MahanteshAngadiGH** [comment]
Please do let me know ... what are you trying to do?

**Comment by raksja** [comment]
@MahanteshAngadiGH 

I'm basically trying to run a py spark job using yarn cluster mode. This issue happens when I execute my spark-submit command from within my EMR cluster. 
I narrowed down to a point where its causing this `ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server`

Reason is I'm adding around 20MB of jar file to the spark.executor.extraClassPath. If it take that out and pass it in --jars then its working fine. 

I tried the stackoverflow @smomen suggested to set driver-memory and executor memory programatically and it didnt help. 

As you mentioned, it looks like because the class loading is taking time, the gateway server is trying to reach it before it even starts up. Am i right? If I'm then how do i make it start after the classloading is done. 

Can you explain a bit more about timeout parameter in hive-site.xml where its used in my spark-submit and how that gets used in pyspark?

**Comment by MahanteshAngadiGH** [comment]
I am not that expert in this space, I am also newbie. I just tried to share
my experience.

My scenario was processing some big log files - around 150 files and total
sizing of 80GB. Processing means, loading them into an hive table and doing
some processing on some of the columns. And writing the data back into
multiple files.

Because of the big size, sometimes the data loading from files into hive
table might be taking time and which might have been throwing java server
error. So "hive.spark.client.server.connect.timeout" might have worked in
my scenario.
,{"classification":"hive-site","properties":
    {"hive.spark.client.server.connect.timeout":"360000ms"}
 }


*Just My Guess (Please don't take it as solution)*In your scenario, the JAR
file itself is too big. That need to be loaded on all the nodes in your EMR
cluster. Because of the big size of the JAR file, it needs more time to be
loaded/deployed onto the nodes. So you need to be considering the timeout
setting of may be YARN. Please try finding out the timeout properties in
relation to YARN. To find an answer/solution to your problem, I was
browsing, I found some pointer (from *stackoverflow*) which might help.

https://stackoverflow.com/questions/28232744/complete-list-of-property-that-is-used-in-hadoop-framework

Try exploring the links in Answer 1

Here are complete list of configuration properties categorized by
configuration files:

   - Properties that go into core-site.xml
   <https://hadoop.apache.org/docs/current/hadoop-project-dist/hadoop-common/core-default.xml>
   - Properties that go into hdfs-site.xml
   <https://hadoop.apache.org/docs/current/hadoop-project-dist/hadoop-hdfs/hdfs-default.xml>
   - Properties that go into mapred-site.xml
   <http://hadoop.apache.org/docs/current/hadoop-mapreduce-client/hadoop-mapreduce-client-core/mapred-default.xml>
   - Properties that go into yarn-site.xml
   <http://hadoop.apache.org/docs/current/hadoop-yarn/hadoop-yarn-common/yarn-default.xml>


For your scenario, try to find out timeout properties in " yarn-site.xml
<http://hadoop.apache.org/docs/current/hadoop-yarn/hadoop-yarn-common/yarn-default.xml>
".

Do please let me know, what do you think and how you resolved your issue.

**Comment by raksja** [comment]
Thanks @MahanteshAngadiGH for detailed response. I tried exactly same with yarn timeout parameters etc. 
But none of them helped, then I tried to include some other huge jars and they didnt have any issue like this. So finally figured out by trying out in different modes (local/client) and culprit is a netty jar thats included and after i shaded it worked fine. :)

Reference for folks who are encountering this issue, reason why i got this Connection Refused on Yarn cluster mode is because my container got killed abruptly (no logs nothing) and that caused py4j listener to not able to connect after it started because server is dead already.

**Comment by userofgithub1** [comment]
@MahanteshAngadiGH  Thank you for your detailed answers. But I'm a beginner with all the sparky stuff. How do you exactly modify the "hive.spark.client.server.connect.timeout" configuration (by code or what) please give example.

Many thanks Mahantesh :)

**Comment by userofgithub1** [comment]
Just for future reference, I solved it by:
('spark.executor.memory', '8g'),('spark.driver.memory','8g'),("hive.spark.client.server.connect.timeout","360000ms")

Good luck,

**Comment by MahanteshAngadiGH** [comment]
By looking at your message, I feel you solved the issue. Is this the case
or still you are looking for the solution.

**Comment by MahanteshAngadiGH** [comment]
Oh ... cool. Makes sense. Thanks for the information.

**Comment by anuthaharinimn** [comment]
hi im dockerising the python srrvices its depends on the java , ifhavaruns
then thatpython service will run , its microservice arvhitecture , if i
dockerise this services java container will exit always , how can i achieve
this thing with highly availablity??

**Comment by AyaAlqurashi** [comment]
hey guys, could u please help me in solving this problem 
firstly i had a problem related to memory , because when i'm trying to read a small file no problem occur , however when i'm trying to read 8G file it gives me this problem  
-----------
Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.runJob.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 29 in stage 1.0 failed 1 times, most recent failure: Lost task 29.0 in stage 1.0 (TID 31, localhost, executor driver): java.io.IOException: Unable to delete C:\Users\HP\AppData\Local\Temp\blockmgr-cfeb7cb6-2c26-4a52-a61c-c14fdb01e1cb\07\temp_shuffle_d28cb0e4-cdc1-4817-9953-f3d71839b92c
at org.spark_project.guava.io.Files.move(Files.java:656)
	at org.apache.spark.shuffle.sort.UnsafeShuffleWriter.mergeSpills(UnsafeShuffleWriter.java:298)
	at org.apache.spark.shuffle.sort.UnsafeShuffleWriter.closeAndWriteOutput(UnsafeShuffleWriter.java:237)
	at org.apache.spark.shuffle.sort.UnsafeShuffleWriter.write(UnsafeShuffleWriter.java:190)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:109)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

-------------
i tried to increase the memory via spark submit args but it didn't help

**Comment by Andy2018f** [comment]
I solved the problem changing the python path that i used with spyder/anconda to Continuum\\anaconda3
Basically you need to check if you have py4j in your share file in python.
Good luck

**Comment by pavan64pavan** [comment]
Okay if anyone is facing the error as below then the solution is to check if you have different versions of Java and keep only one.

ERROR:
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:54428)

**Comment by gvijay1788** [comment]
> Hi,
> 
> you are trying to connect to port 25335 on the Python side, but the Java side is listening on the default port, 25333. To fix this, either use the default port on both side, or start the GatewayServer on port 25335 using one of the many constructors.
I am just running a sql using 
I am getting similar error, could you please provide sample code to fix this- 
df = spark.sql(query)

**Error message :** 
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
/opt/spark-3.0.0/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py in _get_connection(self)
    976         try:
--> 977             connection = self.deque.pop()
    978         except IndexError:

IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

ConnectionRefusedError                    Traceback (most recent call last)
/opt/spark-3.0.0/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py in start(self)
   1114         try:
-> 1115             self.socket.connect((self.address, self.port))
   1116             self.stream = self.socket.makefile("rb")

ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Py4JNetworkError                          Traceback (most recent call last)
<ipython-input-38-95c5cb6bfd4c> in <module>
      3     sparkcluster_config=cluster_configs_template(size='small'),
----> 4     conn_id='mdl2_hive_metastore_prod', # this is the 'nonprod' mdl, for prod, use 'mdl2_hive_metastore_prod'
      5 )

/opt/pyenv/versions/3.7.4/lib/python3.7/*****/spark_Hook.py in __init__(self, conn_id, spark_master_uri, enable_parquet_metadata, builder_func, input_data_contract, spark_session, sparkcluster_config, spark_confs, cluster_id, driver_cpu, driver_memory, backend_type, **kwargs)
    343         if create_spark_session:
--> 344             self.spark_session = self._get_spark_session()
    345         else:

/opt/pyenv/versions/3.7.4/lib/python3.7/***/spark_hook.py in _get_spark_session(self)
    576         if self.conn_id:
--> 577             spark = self.builder.enableHiveSupport().getOrCreate()
    578         else:

/opt/spark-3.0.0/python/pyspark/sql/session.py in getOrCreate(self)
    181                     else:
--> 182                         sparkConf = SparkConf()
    183                         for key, value in self._options.items():

/opt/spark-3.0.0/python/pyspark/conf.py in __init__(self, loadDefaults, _jvm, _jconf)
    115                 # JVM is created, so create self._jconf directly through JVM
--> 116                 self._jconf = _jvm.SparkConf(loadDefaults)
    117                 self._conf = None

/opt/spark-3.0.0/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py in __getattr__(self, name)
   1694             proto.REFL_GET_UNKNOWN_SUB_COMMAND_NAME + name + "\n" + self._id +
-> 1695             "\n" + proto.END_COMMAND_PART)
   1696         if answer == proto.SUCCESS_PACKAGE:

/opt/spark-3.0.0/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py in send_command(self, command, retry, binary)
   1030         """
-> 1031         connection = self._get_connection()
   1032         try:

/opt/spark-3.0.0/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py in _get_connection(self)
    978         except IndexError:
--> 979             connection = self._create_connection()
    980         return connection

/opt/spark-3.0.0/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py in _create_connection(self)
    984             self.gateway_parameters, self.gateway_property)
--> 985         connection.start()
    986         return connection

/opt/spark-3.0.0/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py in start(self)
   1126             logger.exception(msg)
-> 1127             raise Py4JNetworkError(msg, e)
   1128 

Py4JNetworkError: An error occurred while trying to connect to the Java server (127.0.0.1:45969)

During handling of the above exception, another exception occurred:

IndexError                                Traceback (most recent call last)
/opt/spark-3.0.0/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py in _get_connection(self)
    976         try:
--> 977             connection = self.deque.pop()
    978         except IndexError:

IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

ConnectionRefusedError                    Traceback (most recent call last)
/opt/spark-3.0.0/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py in start(self)
   1114         try:
-> 1115             self.socket.connect((self.address, self.port))
   1116             self.stream = self.socket.makefile("rb")

ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Py4JNetworkError                          Traceback (most recent call last)
<ipython-input-38-95c5cb6bfd4c> in <module>
     12 except Exception as e:
     13     print(e)
---> 14     spark.stop()

/opt/spark-3.0.0/python/pyspark/sql/session.py in stop(self)
    702         self._sc.stop()
    703         # We should clean the default session up. See SPARK-23228.
--> 704         self._jvm.SparkSession.clearDefaultSession()
    705         self._jvm.SparkSession.clearActiveSession()
    706         SparkSession._instantiatedSession = None

/opt/spark-3.0.0/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py in __getattr__(self, name)
   1693             proto.REFLECTION_COMMAND_NAME +
   1694             proto.REFL_GET_UNKNOWN_SUB_COMMAND_NAME + name + "\n" + self._id +
-> 1695             "\n" + proto.END_COMMAND_PART)
   1696         if answer == proto.SUCCESS_PACKAGE:
   1697             return JavaPackage(name, self._gateway_client, jvm_id=self._id)
.
.
.
.

Py4JNetworkError: An error occurred while trying to connect to the Java server (127.0.0.1:45969)
```

Please suggest.
