### ISSUE TITLE
python helper function to show method signature  

### ISSUE THREAD

**Issue by pbirnie** [bartdag/py4j#285]
I believe it would be useful to have a python helper function 

display_member_signature(py4j.java_gateway.JavaMember):
    returns string listing parameters the method requires

-- details --
I am working in a repl with pyspark (uses py4j)
it would be useful to see what parameters the method is expecting 

def pretty_df_show(df, n):
    return df._jdf.showString(n, 40)

The dataframe showString above takes 2 parameters - but knowing which parameters to provide is currently not that easy as you need to go into the spark source  code - and the number of parameters has changed depending on the version of the code

dir(df._jdf) will show me all the methods available - because there is a py4j.java_gateway.JavaMember per method
BUT
if in python I call 
inspect.getargspec(df._jdf.showString)

I get 
TypeError: <py4j.java_gateway.JavaMember object at 0x0000000009F81F60> is not a Python function

**Comment by jonahkichwacoders** [comment]
I don't know if this helps you, but what you are hitting, in the first instance, is a limitation of Python 2. Python 2 does not allow you to inspect callable objects (classes with __call__) in that way.

Using Python 3 will warn you that `inspect.getargspec` is deprecated and recommend `inspect.signature`. `inspect.signature` does not give you such errors and indeed shows you the *Python* signature. 

However, the Python signature is *always* `(*args)` because the signature is obtained by looking at the callable object, which in this case is of type `JavaMember` and gets the arguments to the `__call__` method, which is always `(*args)`.

I don't know if it is possible to provide custom Signature objects that would use such inspection info. However one challenge to keep in mind is that there is a 1 to many mapping from Python to Java.

---

In the meantime, you could present the `__doc__` field of the `JavaMember` to your REPL. That is what other REPLs have done (like PyDev and IPython, for which I originally contribute the `__dir__` and `__doc__` members in #157)

For example, given a class with:

	public int method7(int i) //...
	public int method7(String s) //...
	public int method7(Object o) //...
	public int method7(long l) //...

The `obj.method7.__doc__` provides this info, showing each of the overloads:
```

Help on class ExampleClass in package py4j.examples:

ExampleClass {
|  
|  Methods defined here:
|  
|  method7(Object) : int
|  
|  method7(String) : int
|  
|  method7(long) : int
|  
|  method7(int) : int
|  
|  ------------------------------------------------------------
|  Fields defined here:
|  
|  ------------------------------------------------------------
|  Internal classes defined here:
|  
|  StaticClass
|  
}


```

(Those examples are from the Py4J source, see java_help_test and java_dir_test)

**Comment by bartdag** [comment]
Thanks @jonahkichwacoders ! Please reopen if needed.
