### ISSUE TITLE
Efficient way to transfer images from Java to Python

### ISSUE THREAD

**Issue by bryantChhun** [bartdag/py4j#331]
On the java side i'm using ByteArrayOutputStream (and .toByteArray()) to serialize the image data.  I populate an ArrayDeque with this serialized image data (1000 images) and then use python to pop-read each byte array.

The python code is quite bare: simple loop to call and exhaust the ArrayDeque.  I don't even assign the byte array or convert it via numpy.

The performance on 1000 images (524288 bytes each) is about 50ms per image, or roughly 100ms per 1MB.

My question is:  is it possible to improve this data throughput through either java or python optimizations?  At this point i'm thinking about writing memory mapped files to disk and reading that way... can Py4J mediate this kind of exchange?  I was trying to avoid disk write, but maybe it's not that bad a thing....

**Comment by bartdag** [comment]
If you are reading a bytearray, Py4J is encoding it with base64. 100 ms per 1Mb seems a bit slow so maybe there is some optimization to make in the loop (like assigning the method you are calling to a variable and then calling this variable), but this is currently the fastest way to use Py4J for this scenario (which is not really fast).

There are a couple of alternative solutions:
1. I'm unfortunately stuck with Java 6 for now because of users using this old version, but if you want to edit the source code, you could use Java native base64 conversion (we had to rely on a third-party library that is slower when we introduce that conversion). I will likely drop Java 6 & 7 soonish.

2. Other users have used alternative methods to transfer binary payload: memory mapped file, writing the whole thing to the disk and then reading it from python, side socket that only sends binary data.

3. I had started a major refactoring to switch to a binary protocol, but due to the lack of funding, this initiative is put on ice for now.

**Comment by bryantChhun** [comment]
Thanks for the reply!  This is very informative.

I'll try your suggestion to assign the method to a variable...

The solution i've settled on for now involves: java side writing raw data to RAMdisk and sending metadata through Py4J.  Python side receives metadata and fetches raw data via np.memmap.  The whole process is blazing fast...

Eventually i'll give the sockets a shot and see how it compares....but this makes more sense when we are doing IPC across multiple boxes.
